### ISSUE TITLE
some touchups for React

### ISSUE THREAD

**Issue by erikyuzwa** [evarghese563/StudioGhibli#1]
Hey I'm pretty sure the empty white page that's showing up on application start is some minor React issues that could be addressed:

The `index.js` could be updated to:
```
<React.StrictMode>
      <BrowserRouter>
          <App />
      </BrowserRouter>
  </React.StrictMode>
```

and then in `App.js`:
```
<div className="App">
        <Navbar />
        <Routes>
          <Route exact path='/' element={<GhibliModal/>}></Route>
          <Route exact path='/aggrid' element={<Aggrid />}></Route>
        </Routes>
      </div>
```

**Comment by erikyuzwa** [comment]
Then the following comes up for me

![Screenshot 2022-10-11 110022](https://user-images.githubusercontent.com/962434/195154526-4c806981-daaf-4218-b4d6-cfad982b923b.png)

**Comment by evarghese563** [comment]
Hey I fixed the issues but the war files are still not showing up. I am attaching 2 war files to my releases could you please check if they run? 
web.war war is just the react frontend
Ghibli.war is react packaged into spring boot

**Comment by erikyuzwa** [comment]
closing to open new one against latest
